# Generated by Django 4.2.1 on 2023-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_storyai_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyai',
            name='story',
            field=models.TextField(blank=True, max_length=650, null=True),
        ),
    ]
